#!/usr/bin/env bash
# Displays domain information

dom_info () {
    line=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\t ' '\n' | tail -n2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    dom_info "$1" "www"
    dom_info "$1" "lb-01"
    dom_info "$1" "web-01"
    dom_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    dom_info "$1" "$2"
fi
