#!/usr/bin/env bash
# installing HAproxy
sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 1654-web-01 35.243.167.75 check\n\tserver 1654-web-02ubuntu35.196.225.34 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
