#!/usr/bin/env bash
# set nginx user as service runner

pkill apache2
sudo service nginx stop
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx chmod 644 /etc/nginx/nginx.conf
sudo -u nginx sed -i "1s/.*/user nginx;/" /etc/nginx/nginx.conf
sudo service nginx start
sudo service nginx stop
sudo -u nginx service nginx start
